language: java
jdk: openjdk8
dist: xenial
install:
  # Installing Android SDK
  - curl https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip --output $HOME/android-sdk.zip
  - unzip -qq $HOME/android-sdk.zip -d $HOME/android-sdk
  - export ANDROID_SDK_HOME=$HOME/android-sdk
  - export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/21.3.6528147
  # Installing necessary components of Android SDK
  - function installAndroidComponent() { yes | ${ANDROID_SDK_HOME}/tools/bin/sdkmanager --sdk_root=${ANDROID_SDK_HOME} $1 > /dev/null; }
  - installAndroidComponent "ndk;21.3.6528147"
  - installAndroidComponent "cmake;3.10.2.4988404"
  # Installing meson, ninja and nasm that are necessary for libdav1d building
  - sudo apt-get install python3-pip python3-setuptools python3-wheel ninja-build
  - sudo pip3 install meson==0.53.2
  - curl http://archive.ubuntu.com/ubuntu/pool/universe/n/nasm/nasm_2.14.02-1_amd64.deb --output $HOME/nasm_2.14.02-1_amd64.deb
  - sudo dpkg -i $HOME/nasm_2.14.02-1_amd64.deb
script:
  - ./ffmpeg-android-maker.sh -dav1d
